### ISSUE TITLE
NamedTuple error

### ISSUE THREAD

**Issue by confact** [vladfaust/stripe.cr#2]
Get this error when doing a create token call:
```
Called macro defined in src/stripe/methods/core/tokens/create_card_token.cr:6:20

 6 | validate card, {{T}} do

Which expanded to:

 > 1 | NamedTuple(number: String, exp_month: Int32, exp_year: Int32, cvc: Int32)
       ^
Error: NamedTuple(T).class is not a generic type, it's a class
```
I am working on adding more methods and classes for a merge request to your repo on confact/stripe.cr as i think me, stripe and the crystal community will win on a stripe crystal library.

**Comment by confact** [comment]
I think is because of crystal >=30.1 changes.

**Comment by vladfaust** [comment]
That error is absurd for me. Should look into https://github.com/vladfaust/stripe.cr/blob/master/src/stripe.cr#L18

**Comment by confact** [comment]
@vladfaust so what could be the issue? How can I fix this? I can't find the problem.

**Comment by vladfaust** [comment]
You may want to add debug prints to the macro I've mentioned. Looks like Crystal macros don't like `.named_args` call to the passed NamedTuple. I don't know why. Moreover, it worked before, so...
